import { readdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { IntelligenceItemV1Schema } from './schemas.ts';
import {
  assertSendableBatch,
  DeletionReceiptV1Schema,
  ReconciliationInventoryV1Schema,
  SyncAckV1Schema,
  verifySyncOperationDigest,
} from './wire.ts';

/**
 * Retained fixtures are the compatibility evidence for a wire version. They are written once, when
 * that version is prepared, and never edited afterwards: a fixture regenerated by the code under
 * test proves only that the code agrees with itself. They also cannot be created honestly after
 * publication, because by then the question is what the released version actually accepted.
 *
 * Every operation type and every top-level message therefore needs one here before v1 ships.
 */
const fixtures = new URL('../fixtures/v1/', import.meta.url);
const read = (name: string): unknown =>
  JSON.parse(readFileSync(new URL(name, fixtures), 'utf8')) as unknown;

const BATCHES = {
  'control-batch.json': ['consent.put'],
  'control-lifecycle-batch.json': ['consent.put', 'item.delete', 'consent.revoke', 'scope.delete'],
  'control-personal-scope-batch.json': ['consent.put'],
  'data-batch.json': ['item.put'],
} as const;

const MESSAGES = {
  'deletion-receipt.json': DeletionReceiptV1Schema,
  'reconciliation-inventory.json': ReconciliationInventoryV1Schema,
  'sync-ack-accepted.json': SyncAckV1Schema,
  'sync-ack-rejection.json': SyncAckV1Schema,
} as const;

describe('retained v1 fixtures', () => {
  it('covers every fixture file, so a new one cannot be added without being checked', () => {
    expect(readdirSync(fileURLToPath(fixtures)).sort()).toEqual(
      [...Object.keys(BATCHES), ...Object.keys(MESSAGES)].sort(),
    );
  });

  for (const [name, types] of Object.entries(BATCHES)) {
    it(`accepts ${name} and verifies every digest`, () => {
      const batch = assertSendableBatch(read(name));
      expect(batch.operations.map((operation) => operation.type)).toEqual(types);
      for (const operation of batch.operations) {
        expect(verifySyncOperationDigest(operation)).toBe(true);
      }
    });
  }

  for (const [name, schema] of Object.entries(MESSAGES)) {
    it(`accepts ${name}`, () => {
      expect(schema.parse(read(name))).toBeTruthy();
    });
  }

  it('covers every sync operation type exactly once across the batch fixtures', () => {
    const covered = Object.values(BATCHES).flat();
    expect([...new Set(covered)].sort()).toEqual([
      'consent.put',
      'consent.revoke',
      'item.delete',
      'item.put',
      'scope.delete',
    ]);
  });

  it('pins a decision item carrying every field a consumer must handle', () => {
    const batch = assertSendableBatch(read('data-batch.json'));
    const operation = batch.operations[0];
    if (operation?.type !== 'item.put') throw new Error('data fixture must carry an item.put');
    const item = IntelligenceItemV1Schema.parse(operation.item);
    if (item.kind !== 'decision') throw new Error('data fixture must carry a decision');

    // Selected and rejected options stay structurally distinct, and a deferred or unknown
    // disposition can never be read as the chosen one.
    expect(item.selected).not.toBe('');
    expect(item.alternatives.map((alternative) => alternative.disposition)).toEqual([
      'rejected',
      'deferred',
      'unknown',
    ]);
    // Repeated citation of one source must not read as independent corroboration.
    expect(new Set(item.evidence.map((evidence) => evidence.independenceId)).size).toBeLessThan(
      item.evidence.length,
    );
    expect(item.evidence.some((evidence) => evidence.role === 'contradicts')).toBe(true);
    expect(item.evidence.some((evidence) => evidence.authority === 'user-explicit')).toBe(true);
    // Optional temporal and link fields are exercised, not left to a later version to discover.
    expect(item.effectiveUntil).toBeDefined();
    expect(item.lifecycle.validUntil).toBeDefined();
    expect(item.links.map((link) => link.relation)).toContain('corrects');
  });

  it('pins both arms of the personal scope union', () => {
    const scopes = ['control-personal-scope-batch.json', 'control-batch.json'].map((name) => {
      const operation = assertSendableBatch(read(name)).operations[0];
      if (operation?.type !== 'consent.put') throw new Error('expected consent.put');
      return operation.grant.scope.kind;
    });
    expect(scopes.sort()).toEqual(['personal', 'project']);
  });

  it('keeps transport acknowledgement separate from deletion completion', () => {
    const ack = SyncAckV1Schema.parse(read('sync-ack-rejection.json'));
    expect(ack.rejection?.retryable).toBe(false);
    expect(ack.reconciliationRequired).toBe('inventory-mismatch');
    const receipt = DeletionReceiptV1Schema.parse(read('deletion-receipt.json'));
    expect(receipt.sinks).toHaveLength(6);
    expect(Object.keys(ack)).not.toContain('deleted');
  });
});
