import type { ReviewGroup, SessionView, StripView, VerdictView } from '@salidium/core';
import { useState } from 'react';
import { durationMs, shortHome, timeOfDay } from '../lib/format.ts';
import { useClamped } from '../lib/useClamped.ts';
import type { Detail, PanelId } from '../store/appStore.ts';
import {
  BeforeAfter,
  Converge,
  Chain as FlowChain,
  Legend,
  type Marks,
  Tree,
} from './FlowDiagram.tsx';
import { Disclosure } from './Sections.tsx';
import { SessionFlow } from './SessionFlow.tsx';
import { CheckLanes, Coverage, FileChurn } from './Visuals.tsx';

/**
 * The generated explanation, and the only canvas on the page.
 *
 * It is also the only content in the app written rather than observed, so it is held apart: one
 * region, one attribution at its foot, and nothing observed mixed into it. It never contributes to
 * Verified, Left or Review — those stay deterministic, below, and are not reachable from here.
 *
 * Each facet gets the shape that fits it. Why is a chain unless the agent found concurrent causes,
 * in which case it is lanes converging on a trunk. How is the component the change centres on with
 * its operations fanning out beneath. An abandoned approach is drawn above its replacement so the
 * two paths can be read step against step.
 */
export function Explained({ ex }: { ex: NonNullable<SessionView['explained']> }) {
  const ac = ex.approachChange;
  const converging = ex.why.lanes.length > 1;
  const hasWhy = ex.why.chain.length > 0 || ex.why.lanes.length > 0;
  const marks: Marks = {
    junction: converging,
    outcome: Boolean(ac),
  };
  return (
    <section className="ex" aria-label="Generated explanation">
      <p className="ex-what">{ex.what.summary}</p>
      {ex.what.currently && (
        <p className="ex-now">
          <span className="ex-now-key">Now</span>
          {ex.what.currently}
        </p>
      )}

      {hasWhy && (
        <section className="ex-block" id="sec-why">
          <ExHead title="Why" summary={ex.why.summary} />
          {converging ? (
            <Converge lanes={ex.why.lanes} trunk={ex.why.chain} />
          ) : (
            <FlowChain steps={ex.why.chain} />
          )}
        </section>
      )}

      {ex.how.steps.length > 0 && (
        <section className="ex-block" id="sec-how">
          <ExHead title="How" summary={ex.how.summary} />
          <Tree root={ex.how.root} steps={ex.how.steps} />
        </section>
      )}

      {ac && (
        <section className="ex-block" id="sec-approach">
          <ExHead title="Approach changed" />
          <BeforeAfter
            from={ac.from}
            fromSteps={ac.fromSteps}
            to={ac.to}
            toSteps={ac.toSteps}
            why={ac.why}
          />
        </section>
      )}

      <footer className="ex-foot">
        <Legend marks={marks} />
        {/*
         * The protocol requires this block to say it is `explained` rather than observed, and one
         * word does it. It read "Written by <model> from the evidence below, not observed": the
         * middle clause describes method rather than provenance, and the evidence is literally
         * below it; "generated" is the term the README and the architecture doc already use for
         * this block, and it carries "not observed" without spending a sentence on it. The model
         * id names its own vendor, so there is no separate Claude-or-Codex label to print.
         */}
        <p className="ex-mark">Generated by {ex.model}</p>
      </footer>
    </section>
  );
}

/** A section rule with its name, and the one line the model wrote about it. */
function ExHead({ title, summary }: { title: string; summary?: string }) {
  return (
    <header className="ex-head">
      <h2 className="ex-title">{title}</h2>
      {summary && <p className="ex-summary">{summary}</p>}
    </header>
  );
}

/**
 * The quantities, in the supporting inspector beside the explanation. A count of files answers
 * "how much" while the page answers "what and why", so the two get parallel space rather than one
 * being buried beneath the other.
 *
 * The raw count of ingested events used to sit in this rail and has been dropped. It was
 * `latestSeq + 1` — how many canonical records Salidium stored — which is a fact about the pipeline
 * and not about the session: it counts hook payloads and transcript lines, so a long stretch of
 * reading files outscores a turn that rewrote a module, and no reader can act on either number.
 * What a human actually needs to know about ingest is whether any of it was lost or hidden, and
 * that is what the notes below already say, in words, and only when there is something to say.
 */
export function Telemetry({ view }: { view: SessionView }) {
  const s = view.strip;
  const v = s.latestVerification;
  const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;
  const notes = [
    view.ingest.redactions > 0 &&
      `${plural(view.ingest.redactions, 'credential-shaped string', 'credential-shaped strings')} redacted`,
    view.ingest.warnings > 0 &&
      `${plural(view.ingest.warnings, 'record', 'records')} could not be read`,
    view.ingest.compactions > 0 &&
      plural(view.ingest.compactions, 'context compaction', 'context compactions'),
  ].filter(Boolean) as string[];
  return (
    <div className="tm">
      <section className="tm-group" aria-labelledby="tm-changes">
        <h3 className="tm-title" id="tm-changes">
          Changes
        </h3>
        <dl className="tm-grid">
          <Quantity label="Files">
            <span className="num">{s.filesChanged}</span>
          </Quantity>
          <Quantity label="Added">
            <span className="tm-add">+{s.linesAdded}</span>
          </Quantity>
          <Quantity label="Removed">
            <span className="tm-del">−{s.linesRemoved}</span>
          </Quantity>
        </dl>
      </section>

      <section className="tm-group" aria-labelledby="tm-activity">
        <h3 className="tm-title" id="tm-activity">
          Activity
        </h3>
        <dl className="tm-grid">
          <Quantity label="Duration">
            {view.report.runtimeMs === undefined ? (
              <span className="tm-unknown">unknown</span>
            ) : (
              <span className="num">{durationMs(view.report.runtimeMs)}</span>
            )}
          </Quantity>
          <Quantity label="Commits">
            <span className="num">{s.commits}</span>
          </Quantity>
          <Quantity label="Turns">
            <span className="num">{s.turns}</span>
          </Quantity>
        </dl>
      </section>
      {/*
       * What the agent consumed, where the rest of the measured totals already are.
       *
       * It was reachable only from the explainer's own settings popover, which answers "what does
       * the feature cost" and not "what did this session consume". Both are useful facts and
       * belong on their respective surfaces.
       *
       * Tokens are observed and print as fact. No figure in currency appears here: that would be
       * Salidium's own arithmetic over a price table it does not carry, and on a subscription no
       * dollar is charged. The section is omitted entirely when nothing was observed.
       */}
      {view.usage && (
        <section className="tm-group" aria-labelledby="tm-model">
          <h3 className="tm-title" id="tm-model">
            Model
          </h3>
          <dl className="tm-grid is-wide">
            <Quantity label="Responses">
              <span className="num">{view.usage.messages.toLocaleString()}</span>
            </Quantity>
            <Quantity label="In">
              <span className="num">{view.usage.inputTokens.toLocaleString()}</span>
            </Quantity>
            <Quantity label="Out">
              <span className="num">{view.usage.outputTokens.toLocaleString()}</span>
            </Quantity>
            <Quantity label="Cache read">
              <span className="num">{view.usage.cacheReadTokens.toLocaleString()}</span>
            </Quantity>
            <Quantity label="Cache write">
              <span className="num">{view.usage.cacheWriteTokens.toLocaleString()}</span>
            </Quantity>
          </dl>
        </section>
      )}
      {v && (
        <section className="tm-group" aria-labelledby="tm-check">
          <h3 className="tm-title" id="tm-check">
            Latest check
          </h3>
          <div className="tm-check">
            <span className="tm-check-method">{v.method}</span>
            <span className={`v-${v.outcome}`}>{v.outcome}</span>
            <span className="num">{timeOfDay(v.at)}</span>
          </div>
        </section>
      )}
      {notes.length > 0 && (
        <section className="tm-group" aria-labelledby="tm-handling">
          <h3 className="tm-title" id="tm-handling">
            Data handling
          </h3>
          <ul className="tm-note-list">
            {notes.map((note) => (
              <li key={note}>{note}</li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}

function Quantity({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="tm-quantity">
      <dt>{label}</dt>
      <dd>{children}</dd>
    </div>
  );
}

/** The four pieces of Evidence, each opened on its own from the panel's rail. */
export function EvidenceCoverage({
  view,
  onRef,
}: {
  view: SessionView;
  onRef: (ref: string) => void;
}) {
  const failing = [
    ...new Set(
      view.left.items
        .filter((i) => i.source === 'verification' && i.status === 'failing')
        .map((i) => i.text.replace(/\s.*$/, '').toLowerCase()),
    ),
  ];
  return (
    <Coverage files={view.changes.files} failing={failing} onOpen={(f) => onRef(f.lastCallId)} />
  );
}

export function EvidenceChecks({
  view,
  onRef,
}: {
  view: SessionView;
  onRef: (ref: string) => void;
}) {
  return <CheckLanes runs={view.verified.runs} onOpen={(v) => onRef(v.callId)} />;
}

export function EvidenceChanged({
  view,
  cwd,
  onRef,
}: {
  view: SessionView;
  cwd: string;
  onRef: (ref: string) => void;
}) {
  return (
    <FileChurn
      files={view.changes.files}
      cwd={cwd}
      limit={20}
      onOpen={(f) => onRef(f.lastCallId)}
    />
  );
}

export function EvidenceHappened({
  view,
  onRef,
}: {
  view: SessionView;
  onRef: (ref: string) => void;
}) {
  return (
    <>
      <SessionFlow turns={view.turns} commits={view.changes.commits} onRef={onRef} />
      <Delegated subagents={view.subagents} onRef={onRef} />
    </>
  );
}

/**
 * One column of "where it stands", on its own, because each is now opened by the badge that
 * states its headline rather than read as one of three columns nobody asked for.
 */
export function StatusColumn({
  which,
  view,
  onRef,
}: {
  which: 'checks' | 'left' | 'review';
  view: SessionView;
  onRef: (ref: string) => void;
}) {
  return <StatusBlock view={view} detail={2} onRef={onRef} only={which} />;
}

/*
 * The four outcomes, as a mark and as a word.
 *
 * `partial` had no mark of its own here and fell through to `?`, which is also `unknown` — so the
 * one outcome that means "the output and the exit code disagree" was drawn identically to the one
 * that means "nothing came back". The word exists because the mark is `aria-hidden` and the colour
 * is a class: without it the outcome reached nobody using a screen reader.
 */
const OUTCOME_GLYPH: Record<string, string> = {
  pass: '✓',
  fail: '✕',
  partial: '◐',
  unknown: '?',
};

const OUTCOME_WORD: Record<string, string> = {
  pass: 'passed',
  fail: 'failed',
  partial: 'partial',
  unknown: 'unknown',
};

/*
 * Caveats are recorded as slugs so the rules stay greppable, but a slug is not a sentence. Scope is
 * left out because it is drawn as its own tag beside the row; anything unmapped falls through as
 * the slug rather than being dropped, because a caveat nobody worded is still a caveat.
 */
const CAVEAT_TEXT: Record<string, string> = {
  'exit-inferred': 'exit code not reported, read from the output',
  'exit-masked': 'exit code hidden by a pipe',
  'output-truncated': 'output was truncated',
  'no-summary-parsed': 'no summary line found in the output',
};

function caveatText(caveats: string[]): string {
  return caveats
    .filter((c) => c !== 'scope-partial')
    .map((c) => CAVEAT_TEXT[c] ?? c)
    .join(' · ');
}

/**
 * A long-running session accumulates dozens of flagged commands and unfinished items. Printed in
 * full they turn one column of a three-column row into a wall while the other two end after a
 * line, so Detail shows the head of each list and Source is where the whole of it lives.
 */
const AT_A_GLANCE = 6;

function StatusBlock({
  view,
  detail,
  onRef,
  only,
}: {
  view: SessionView;
  detail: Detail;
  onRef: (ref: string) => void;
  /** Render one column alone, for the panel that badge opens. */
  only?: 'checks' | 'left' | 'review';
}) {
  const summary = view.verified.summary;
  const attention = view.review.groups.filter((g) => g.severity !== 'info');
  const clip = <T,>(items: T[]) => (detail > 1 ? items : items.slice(0, AT_A_GLANCE));
  const more = (n: number) =>
    detail > 1 || n <= AT_A_GLANCE ? null : (
      <li className="rp-none">…{n - AT_A_GLANCE} more, under Records</li>
    );
  const show = (col: 'checks' | 'left' | 'review') => only === undefined || only === col;
  return (
    <div className={`rp-cols${only ? ' is-single' : ''}`}>
      {show('checks') && (
        <div className="rp-block" id="sec-verified">
          <h3 className="rp-title">Verified</h3>
          {summary.length === 0 ? (
            <p className="rp-none">No checks observed.</p>
          ) : (
            <ul className="rp-status">
              {summary.map((v) => {
                const caveat = caveatText(v.caveats);
                return (
                  <li key={v.id} className={`v-${v.outcome}`}>
                    <span className="rp-mark" aria-hidden="true">
                      {OUTCOME_GLYPH[v.outcome] ?? '?'}
                    </span>
                    <button
                      type="button"
                      className="rp-status-label"
                      onClick={() => onRef(v.callId)}
                    >
                      {v.method}
                      {/*
                       * The outcome is carried by a glyph that is `aria-hidden`, a colour, and a
                       * class. All three are invisible to a screen reader, which read "vitest
                       * 3/12" for a failure and "vitest 12/12" for a pass, in the same words. The
                       * word goes inside the button so the control that opens the record says
                       * what it is about.
                       */}
                      <span className="sr-only">{OUTCOME_WORD[v.outcome] ?? v.outcome}</span>
                      {v.counts?.total !== undefined && (
                        <span className="mono rp-counts">
                          {v.counts.passed ?? 0}/{v.counts.total}
                        </span>
                      )}
                    </button>
                    {/*
                     * Scope is not outcome. A run narrowed to a path or a filter passed on what it
                     * ran and says nothing about the rest, and the command it was read from is not
                     * on this row for a reader to judge that for themselves.
                     */}
                    {v.scope === 'partial' && <span className="rp-subset">subset</span>}
                    {/*
                     * An outcome that is not the newest one has to say so, right beside itself. This
                     * row exists because a later run said nothing, and a reader who takes it for the
                     * latest state is worse off than one who was told nothing at all.
                     */}
                    {v.laterUnreadable > 0 && (
                      <span
                        className="rp-stale"
                        title={`${v.laterUnreadable} later ${v.laterUnreadable === 1 ? 'run' : 'runs'} of ${v.method} produced no readable outcome`}
                      >
                        not the latest run
                      </span>
                    )}
                    {/*
                     * Which of the two readings was actually available. A pass read out of a
                     * summary line and a pass read from an exit code are different facts, and this
                     * panel printed the same word for both.
                     */}
                    {caveat && <span className="rp-caveat">{caveat}</span>}
                    {detail > 1 && v.epistemic === 'inferred' && (
                      <span className="rp-derived">derived</span>
                    )}
                  </li>
                );
              })}
            </ul>
          )}
        </div>
      )}

      {show('left') && (
        <div className="rp-block" id="sec-left">
          <h3 className="rp-title">Left</h3>
          {view.left.items.length === 0 ? (
            <p className="rp-none">Nothing recorded.</p>
          ) : (
            <ul className="rp-status">
              {clip(view.left.items).map((i) => (
                <li key={i.id}>
                  <span className="rp-mark" aria-hidden="true">
                    {i.status === 'failing' ? '✕' : i.status === 'in_progress' ? '▸' : '○'}
                  </span>
                  <span>{i.text}</span>
                </li>
              ))}
              {more(view.left.items.length)}
            </ul>
          )}
        </div>
      )}

      {show('review') && (
        <div className="rp-block" id="sec-review">
          <h3 className="rp-title">Review</h3>
          {attention.length === 0 ? (
            <p className="rp-none">Nothing needs you.</p>
          ) : (
            <ul className="rp-status">
              {clip(attention).map((g) => (
                <ReviewGroupRow key={g.rule} group={g} onRef={onRef} />
              ))}
              {more(attention.length)}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

/**
 * What the agents this session delegated to actually came back with.
 *
 * The flow already says "delegated to 3 subagents", which answers how much was handed off and not
 * what came of it — and on a Codex session running a fan-out, the subagents' write-ups are the
 * substance of the work. They were reaching nothing at all until the adapter learned to read them
 * (`rolloutParser.ts`), and a recovered fact that no surface prints is not recovered.
 *
 * A lane with no result is shown saying so rather than omitted: a subagent that ended without
 * reporting is a different thing from one that was never started, and the difference is the whole
 * question of whether its work counted.
 *
 * Each row opens its own record, like everything else on the page. It could not until now, because
 * the projection carried no reference — which made the one section that quotes an agent verbatim
 * the one place a reader had to take the app's word for it. The record is the report where there
 * is one and the record that started the lane where there is not, so the button always opens the
 * thing the row is actually reading from.
 */
function Delegated({
  subagents,
  onRef,
}: {
  subagents: SessionView['subagents'];
  onRef: (ref: string) => void;
}) {
  if (subagents.length === 0) return null;
  const reported = subagents.filter((s) => s.lastMessage).length;
  return (
    <Disclosure
      label={`Delegated to ${subagents.length} ${subagents.length === 1 ? 'agent' : 'agents'}${reported > 0 ? `, ${reported} reported back` : ''}`}
      id="subagents"
    >
      <ul className="rows">
        {subagents.map((s) => (
          <DelegatedRow key={s.id} agent={s} onRef={onRef} />
        ))}
      </ul>
    </Disclosure>
  );
}

/**
 * One delegated agent: who it was, and what it wrote back.
 *
 * Clamped to four lines with a control, like every other quoted statement on the page, and the
 * control appears only when a measurement says something is actually hidden — a subagent's report
 * runs from one line to several hundred words, and a "more" over text with nothing behind it is
 * worse than none.
 */
function DelegatedRow({
  agent,
  onRef,
}: {
  agent: SessionView['subagents'][number];
  onRef: (ref: string) => void;
}) {
  const [open, setOpen] = useState(false);
  const text = agent.lastMessage ?? '';
  const [ref, clamped] = useClamped<HTMLSpanElement>(open, text);
  return (
    <li className="row row-flat is-quote">
      <span className="attrib">{agent.description ?? agent.agentType ?? agent.id}</span>
      {text ? (
        <>
          <span ref={ref} className={`rp-statement-body${open ? ' is-open' : ''}`}>
            {text}
          </span>
          {(clamped || open) && (
            <button type="button" className="link" onClick={() => setOpen(!open)}>
              {open ? 'less' : 'more'}
            </button>
          )}
        </>
      ) : (
        <span className="muted">{agent.endedAt ? 'ended without reporting' : 'still running'}</span>
      )}
      {agent.eventId && (
        <button
          type="button"
          className="link"
          onClick={() => onRef(agent.eventId)}
          aria-label={`Open the record for ${agent.description ?? agent.agentType ?? agent.id}`}
        >
          record
        </button>
      )}
    </li>
  );
}

/**
 * One rule's worth of Review, as one row.
 *
 * A rule that fired once reads exactly as it always did — a sentence and a link to the record. A
 * rule that fired twenty times says so and stays one line, because twenty rows reading "Recursive
 * force delete" is one fact told twenty times, and a column that grows with the length of the
 * session is a column nobody reads to the end of. The count is the point: "cleared a cache before
 * every test run" and "deleted twenty different things" are the same twenty rows and completely
 * different news, and the reader can tell them apart here without opening anything, because the
 * distinct count is printed beside the total.
 *
 * The occurrences are one click away rather than gone. Nothing is dropped; it is ranked.
 */
function ReviewGroupRow({ group, onRef }: { group: ReviewGroup; onRef: (ref: string) => void }) {
  const [open, setOpen] = useState(false);
  const one = group.items[0];
  // A rule that fired once has nothing to summarise and nothing to expand: it is its own detail.
  if (group.occurrences === 1 && one)
    return (
      <li className="is-attn">
        <span className="rp-mark" aria-hidden="true">
          ⚠
        </span>
        <span>{one.summary}</span>
        {one.refs[0] && (
          <button type="button" className="link rp-ev" onClick={() => onRef(one.refs[0] as string)}>
            record
          </button>
        )}
      </li>
    );
  return (
    <li className="is-attn rp-group">
      <span className="rp-mark" aria-hidden="true">
        ⚠
      </span>
      <div className="rp-group-body">
        <button
          type="button"
          className="rp-group-head"
          onClick={() => setOpen((o) => !o)}
          aria-expanded={open}
        >
          <span className="rp-group-label">{group.label}</span>
          {/* Total, then how many of them differ. One number says how loud this is; the pair says
              whether it is one thing repeated, which is what decides if you have to look. */}
          <span className="rp-group-count num">
            {group.occurrences}
            {group.items.length < group.occurrences && (
              <span className="rp-group-distinct"> · {group.items.length} distinct</span>
            )}
          </span>
        </button>
        {open && (
          <ul className="rp-group-items">
            {group.items.map((i) => (
              <li key={i.id}>
                <span className="mono" title={i.instance ?? i.label}>
                  {shortHome(i.instance ?? i.label)}
                </span>
                {i.repeats > 1 && <span className="rp-group-repeats num">×{i.repeats}</span>}
                {i.refs[0] && (
                  <button
                    type="button"
                    className="link rp-ev"
                    onClick={() => onRef(i.refs[0] as string)}
                  >
                    record
                  </button>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>
    </li>
  );
}

/**
 * The badges, where a README puts them: did it work, what still needs a human, what is unfinished.
 *
 * The verdict's tone is the answer and its rule style is the epistemics — a long dash whenever
 * Salidium worked the answer out rather than observing it, because an inferred pass and an
 * observed pass are different facts. All three are observed; none of them can be moved by the
 * generated explanation below.
 *
 * Review and Left are here rather than only in their sections because a reader has five seconds
 * and those are two of the questions they arrive with.
 *
 * Each badge now opens the section it summarises. The doc used to say a tag states a fact and a
 * button performs an action, so the two must not share a shape — a row of facts that reads as a
 * row of controls invites clicks that do nothing. The objection was to clicks that do nothing;
 * these do the obvious thing. It also removes a whole row of buttons that would otherwise repeat,
 * in worse words, what the badges already say: the verdict opens the checks it was read from, the
 * review count opens what needs a human, the unfinished count opens what is left.
 *
 * The verdict's own `record` control went with it. A control inside a control is invalid markup,
 * and it had become a duplicate besides: the panel it now opens lists the runs the verdict was
 * read from, each with the record it came from.
 */
export function VerdictBadge({
  verdict,
  strip,
  onOpen,
}: {
  verdict: VerdictView;
  strip: StripView;
  onOpen: (panel: PanelId) => void;
}) {
  // `because` usually already says how the verdict was reached ("Read from the output; the command
  // reported no exit code"), so the epistemic phrase is only added when nothing else explains it.
  const note = [
    verdict.because,
    strip.waiting?.summary,
    verdict.epistemic === 'inferred' && !verdict.because ? 'Worked out, not observed.' : undefined,
  ]
    .filter(Boolean)
    .join(' ');
  return (
    <div className="masthead-badges">
      <button
        type="button"
        className="tag is-open"
        data-tone={verdict.tone}
        onClick={() => onOpen('checks')}
        title="Open the checks this verdict was read from"
      >
        <span className="tag-strong">{verdict.headline}</span>
        {/*
         * An inferred pass and an observed pass are different facts, and the tone fill cannot say
         * which this is. It goes in the caveat, in words. It was a lone "derived" carrying the
         * app's dashed-underline mark for a derived value, which inside a red tag rendered as a
         * red dashed underline — indistinguishable from a spellchecker calling the word a mistake.
         */}
        {note && <span className="tag-note">{note}</span>}
      </button>
      {strip.reviewOpen > 0 && (
        <button
          type="button"
          className="tag is-open"
          data-tone="attention"
          onClick={() => onOpen('review')}
          title="Things Salidium flagged for a human: failing checks, waiting prompts, destructive commands, claims with no evidence"
        >
          <span className="tag-key">to review</span>
          <span className="num tag-strong">{strip.reviewOpen}</span>
        </button>
      )}
      {strip.remaining > 0 && (
        <button
          type="button"
          className="tag is-open"
          onClick={() => onOpen('left')}
          title="Work the agent recorded as not yet finished"
        >
          <span className="tag-key">unfinished</span>
          <span className="num tag-strong">{strip.remaining}</span>
        </button>
      )}
    </div>
  );
}
