import { z } from 'zod';

/**
 * Epistemic class of a statement shown to the user. This is the backbone of trust in Salidium:
 * every derived object carries one, and the UI renders each class differently.
 *
 * - observed:  a fact recorded by a runtime or by Salidium about the world (a diff, an exit code,
 *              a git SHA). Never generated by a model.
 * - reported:  text authored by the working agent or the user (a goal, a rationale, "tests pass").
 *              Relayed verbatim, attributed, never upgraded to observed by parsing.
 * - inferred:  Salidium's deterministic derivation that involves a heuristic (test-summary regex
 *              counts, "this verification covers that file"). Carries a rule id.
 * - planned:   forward-looking items (todo entries, plan steps).
 * - explained: optional narrative layer (templates today, possibly a model later). Must cite basis.
 */
export const EpistemicSchema = z.enum(['observed', 'reported', 'inferred', 'planned', 'explained']);
export type Epistemic = z.infer<typeof EpistemicSchema>;

/**
 * Built-in providers keep their original stable ids. Extension providers use a mandatory
 * owner/name namespace so independently-developed adapters cannot silently claim a built-in name
 * or collide with one another.
 */
export const BuiltInProviderIdSchema = z.enum(['claude-code', 'codex']);
export type BuiltInProviderId = z.infer<typeof BuiltInProviderIdSchema>;

export const NamespacedProviderIdSchema = z
  .string()
  .regex(
    /^[a-z][a-z0-9-]{0,62}\/[a-z][a-z0-9-]{0,62}$/,
    'extension provider id must be a lowercase owner/name namespace',
  );

export const ProviderIdSchema = z.union([BuiltInProviderIdSchema, NamespacedProviderIdSchema]);
export type ProviderId = z.infer<typeof ProviderIdSchema>;

/** Which channel an event arrived on. Determines latency, completeness and stability caveats. */
export const SourceChannelSchema = z.enum([
  'hook',
  'transcript',
  'rollout',
  'app-server',
  'salidium',
]);
export type SourceChannel = z.infer<typeof SourceChannelSchema>;

/**
 * Where an event came from, precisely enough to drill back to the raw record.
 * `ref` points into the provider's own file when one exists (transcript line, rollout line).
 */
export const EventSourceSchema = z.object({
  provider: ProviderIdSchema,
  channel: SourceChannelSchema,
  /** Provider version that produced the record, when known (e.g. "2.1.233"). */
  version: z.string().optional(),
  ref: z
    .object({
      path: z.string().optional(),
      line: z.number().int().nonnegative().optional(),
      recordId: z.string().optional(),
      /** Identity of the exact provider record at ingestion, before any raw drill-through. */
      recordHash: z
        .string()
        .regex(/^sha256:[0-9a-f]{64}$/)
        .optional(),
    })
    .optional(),
});
export type EventSource = z.infer<typeof EventSourceSchema>;

/**
 * How an exit code was established. Claude Code does not record exit codes for successful Bash
 * calls, and Codex code-mode `exec` hides nested shell exit codes, so "unknown" and "inferred"
 * are first-class values. Never coerce unknown to 0.
 */
export const ExitObservationSchema = z.enum([
  'explicit',
  'inferred-success',
  'inferred-failure',
  'unknown',
]);
export type ExitObservation = z.infer<typeof ExitObservationSchema>;

export const ExitStatusSchema = z.object({
  code: z.number().int().optional(),
  observation: ExitObservationSchema,
});
export type ExitStatus = z.infer<typeof ExitStatusSchema>;
