import { z } from 'zod';

/**
 * The Salidium consumer contract, version 1: a read-only local interface any tool on the same
 * machine can use to read what Salidium understood about a coding-agent session.
 *
 * These schemas are the source of truth. The JSON Schema files under `schema/v1/` are generated from
 * them and a test fails when the two disagree. Both describe exactly what a daemon speaking this
 * contract emits; neither is a description of Salidium's internal state, which stays private.
 *
 * Compatibility, stated once so every schema below can rely on it:
 *
 * - Within major version 1, changes are additive only. A later minor version may add an object
 *   property or a feed message type. It never removes, renames, or retypes a property, never makes
 *   a nullable property non-nullable or the reverse, never adds a value to an enumeration, and
 *   never loosens a bound: a maximum length or count may shrink, never grow, because an older
 *   consumer's validator would reject the longer value.
 * - Consumers must therefore ignore object properties and feed message types they do not know.
 *   The published JSON Schema leaves objects open for exactly that reason.
 * - Every property is always present. A value Salidium does not have is `null`, never an omitted
 *   key, so a missing key is a defect rather than a way of saying "unknown".
 */
export const CONSUMER_CONTRACT = { name: 'salidium.consumer', major: 1, minor: 1 } as const;

/** Every URL in this contract starts here. The major version is part of the path. */
export const CONSUMER_BASE_PATH = '/consumer/v1';

/** The token scheme, so a consumer can recognize a credential without a network call. */
export const CONSUMER_TOKEN_PATTERN = /^salidium_consumer_[0-9a-f]{12}_[0-9a-f]{64}$/;

const Timestamp = z.iso
  .datetime({ offset: false, precision: 3 })
  .describe('UTC, millisecond precision, trailing Z. Lexicographic order is time order.');
const Count = z.number().int().nonnegative();
const Text = (max: number) => z.string().max(max);

/**
 * How Salidium knows a derived value. This is the property a consumer must not flatten: an agent
 * saying tests passed and Salidium observing a passing exit code are different facts.
 *
 * - observed: recorded by a runtime or by Salidium (a diff, an exit code, a commit SHA).
 * - reported: written by the working agent or the user, relayed and attributed, never upgraded.
 * - inferred: Salidium's deterministic derivation that involves a heuristic.
 * - planned: a forward-looking item such as a plan step.
 * - explained: generated by a model at the user's request. Never evidence.
 */
export const ProvenanceSchema = z
  .enum(['observed', 'reported', 'inferred', 'planned', 'explained'])
  .describe('How Salidium knows this value. Render the classes differently; never merge them.');
export type Provenance = z.infer<typeof ProvenanceSchema>;

export const SessionStatusSchema = z
  .enum(['working', 'idle', 'waiting', 'ended', 'unknown'])
  .describe(
    'As of generatedAt. A working session silent for fifteen minutes reads idle, so status can change with time alone.',
  );
export type SessionStatus = z.infer<typeof SessionStatusSchema>;

export const ProviderIdSchema = z
  .string()
  .regex(/^(?:claude-code|codex|[a-z][a-z0-9-]{0,62}\/[a-z][a-z0-9-]{0,62})$/)
  .describe('claude-code, codex, or a namespaced owner/name extension provider.');

/** A provider session id is the provider's own, so it is bounded rather than shaped. */
export const NativeSessionIdSchema = z
  .string()
  .min(1)
  .max(512)
  // biome-ignore lint/suspicious/noControlCharactersInRegex: excluding control characters is the point, and a pattern is what JSON Schema can carry.
  .regex(/^[^\u0000-\u001f\u007f]+$/)
  .describe("The provider's own session id, exactly as the provider wrote it.");

export const NativeIdentitySchema = z
  .object({
    provider: ProviderIdSchema,
    sessionId: NativeSessionIdSchema,
  })
  .describe(
    'The key any tool that launched a session already has. Look a session up by it with the lookup endpoint.',
  );
export type NativeIdentity = z.infer<typeof NativeIdentitySchema>;

export const ExplanationStatusSchema = z
  .enum(['generated', 'generating', 'disabled', 'unavailable', 'failed', 'none'])
  .describe(
    'Outcome of the most recent explanation attempt; none when there has been no attempt. Whether an explanation covers the newest evidence is the report field explanation.current.',
  );
export type ExplanationStatus = z.infer<typeof ExplanationStatusSchema>;

export const VerificationOutcomeSchema = z.enum(['pass', 'fail', 'partial', 'unknown']);

/** One row of the session list, and the identity block every other document repeats. */
export const SessionEntrySchema = z.object({
  id: Text(1100).describe(
    "Salidium's session id. Opaque: use it only to build report URLs, percent-encoded as one path segment.",
  ),
  native: NativeIdentitySchema,
  title: Text(200)
    .nullable()
    .describe(
      "The provider's own session title. Null when the provider gave none: Salidium's interface falls back to the first line of the prompt, and prompts are not part of this contract.",
    ),
  cwd: Text(4096).describe('Working directory the provider recorded for the session.'),
  repositoryRoot: Text(4096)
    .nullable()
    .describe('Git repository root, when Salidium observed one. Null is not "not a repository".'),
  model: Text(200).nullable(),
  status: SessionStatusSchema,
  startedAt: Timestamp.nullable(),
  lastEventAt: Timestamp.nullable(),
  endedAt: Timestamp.nullable(),
  evidenceSeq: Count.describe(
    'Sequence of the newest evidence this entry reflects. It only grows for a given session; a larger value means the report changed.',
  ),
  counts: z.object({
    turns: Count,
    toolCalls: Count,
    filesChanged: Count,
    linesAdded: Count,
    linesRemoved: Count,
    linesRemovedExact: z
      .boolean()
      .describe(
        'False when a provider replaced some file without recording what it held, so linesRemoved is a lower bound rather than a count. Added in 1.1.',
      ),
    reviewOpen: Count.describe('Open review items above informational severity.'),
    remaining: Count.describe('Plan steps still pending or in progress.'),
  }),
  lastVerification: z
    .object({
      outcome: VerificationOutcomeSchema,
      at: Timestamp,
      provenance: ProvenanceSchema,
    })
    .nullable()
    .describe('The most recent check Salidium recognized, in run order. Null when none ran.'),
  explanation: ExplanationStatusSchema,
});
export type SessionEntry = z.infer<typeof SessionEntrySchema>;

/**
 * One attributed sentence. The only agent- or user-authored text the report carries, and always
 * short, redacted, and labelled with who said it.
 */
export const StatementSchema = z.object({
  text: Text(600),
  provenance: z
    .literal('reported')
    .describe('A statement is always something the agent said. Findings are elsewhere.'),
  author: z
    .enum(['agent', 'subagent'])
    .nullable()
    .describe('Who said it. Nothing the user wrote crosses this contract.'),
  at: Timestamp.nullable(),
});
export type Statement = z.infer<typeof StatementSchema>;

export const ExitSchema = z.object({
  code: z.number().int().nullable(),
  observation: z
    .enum(['explicit', 'inferred-success', 'inferred-failure', 'unknown'])
    .describe(
      'Claude Code records no exit code for a successful command and Codex can hide nested codes; unknown is a result, not zero.',
    ),
});

export const VerificationRunSchema = z.object({
  id: Text(512),
  at: Timestamp,
  label: Text(300).describe('Salidium-written, e.g. "45/45 tests passed (vitest)".'),
  method: z.enum(['test', 'typecheck', 'lint', 'build', 'other']),
  runner: Text(120).nullable(),
  outcome: VerificationOutcomeSchema,
  counts: z
    .object({
      passed: Count.nullable(),
      failed: Count.nullable(),
      skipped: Count.nullable(),
      total: Count.nullable(),
    })
    .nullable(),
  scope: z.enum(['full', 'partial', 'unknown']),
  exit: ExitSchema,
  provenance: ProvenanceSchema,
  caveats: z.array(Text(120)),
  stale: z.boolean().describe('Files changed after this run, so it no longer covers them.'),
});
export type VerificationRun = z.infer<typeof VerificationRunSchema>;

/**
 * Where a changed file sits in Git, added in 1.1. Salidium resolves it from the filesystem when the
 * change happens, because agents often write in a worktree or checkout other than the one the
 * session started in, so `session.repositoryRoot` says nothing about a particular file.
 */
export const FileRepositorySchema = z
  .object({
    root: Text(4096).describe('Top level of the Git working tree that holds the file.'),
    path: Text(4096).describe('The file relative to root, with / separators.'),
    mainRoot: Text(4096)
      .nullable()
      .describe(
        'When root is a linked worktree, the repository it belongs to: the working tree that owns the shared Git directory, or that directory itself for a bare repository. Null for a main working tree.',
      ),
    provenance: z.literal('observed'),
  })
  .describe(
    'Resolved from Git pointer files on disk when the change was live, without running git. Null when no repository held the file, when the change was imported from history, or when Salidium could not tell; nothing is guessed. Added in 1.1.',
  );
export type FileRepository = z.infer<typeof FileRepositorySchema>;

export const ChangedFileSchema = z.object({
  path: Text(4096),
  repository: FileRepositorySchema.nullable(),
  changeCount: Count,
  linesAdded: Count,
  linesRemoved: Count,
  linesRemovedExact: z
    .boolean()
    .describe(
      'False when some change replaced this file without recording what it held, so linesRemoved is a lower bound. Added in 1.1.',
    ),
  kinds: z.array(z.enum(['add', 'update', 'delete', 'move'])),
  lastChangedAt: Timestamp,
  coverage: z
    .object({
      verifiedAfter: z.boolean(),
      by: Text(300).nullable().describe('Label of the covering check, when there is one.'),
      provenance: z.literal('inferred'),
    })
    .describe(
      'Whether a full-scope passing test, build, or typecheck ran after the last change. Always inferred: a run covering a file is a heuristic.',
    ),
  reason: StatementSchema.nullable().describe(
    'Nearest rationale the agent gave before the change, bound to the file by time. Always reported, and the binding itself is a heuristic.',
  ),
});
export type ChangedFile = z.infer<typeof ChangedFileSchema>;

export const ReviewGroupSchema = z.object({
  rule: Text(120).describe('Stable rule id, e.g. verification-failed or destructive:rm-rf.'),
  label: Text(300),
  severity: z.enum(['info', 'low', 'medium', 'high']),
  occurrences: Count,
  latestAt: Timestamp,
  items: z.array(
    z.object({
      id: Text(512),
      label: Text(300),
      instance: Text(200)
        .nullable()
        .describe(
          'The short fragment that is the finding itself, e.g. the destructive command segment. Clipped and redacted.',
        ),
      createdAt: Timestamp,
      provenance: ProvenanceSchema,
      repeats: Count,
    }),
  ),
});
export type ReviewGroup = z.infer<typeof ReviewGroupSchema>;

export const RemainingItemSchema = z.object({
  id: Text(600),
  text: Text(600),
  status: z.enum(['pending', 'in_progress', 'failing', 'reported']),
  provenance: ProvenanceSchema,
  source: z.enum(['plan', 'verification', 'agent']),
});

const Step = Text(200);

export const ExplanationContentSchema = z.object({
  what: z.object({ summary: Text(600), currently: Text(600).nullable() }),
  why: z.object({
    summary: Text(600),
    lanes: z.array(z.object({ title: Text(100), steps: z.array(Step) })),
    chain: z.array(Step),
  }),
  how: z.object({ summary: Text(600), root: Text(200).nullable(), steps: z.array(Step) }),
  approachChange: z
    .object({
      from: Text(200),
      fromSteps: z.array(Step),
      why: Text(600),
      to: Text(200),
      toSteps: z.array(Step),
    })
    .nullable(),
});

export const ExplanationSchema = z
  .object({
    status: ExplanationStatusSchema,
    provenance: z.literal('explained'),
    current: z
      .boolean()
      .describe('The content covers the newest evidence. False when content is null.'),
    basedOnSeq: Count.nullable(),
    generatedAt: Timestamp.nullable(),
    model: Text(120).nullable(),
    content: ExplanationContentSchema.nullable().describe(
      'The newest generated Why and How. Present with status generating or failed when an older explanation exists.',
    ),
  })
  .describe(
    'Optional model-written narrative. Salidium never calls a model because a consumer read a report.',
  );
export type Explanation = z.infer<typeof ExplanationSchema>;

/**
 * The repository state at one session boundary, read by Salidium from the session's own working
 * directory when the boundary happened. Added in 1.1.
 */
export const RevisionAnchorSchema = z.object({
  root: Text(4096)
    .nullable()
    .describe(
      'The repository this anchor read, as Git reported its top level. A session can move between repositories, so this can differ from session.repositoryRoot and between the two anchors. Null when it could not cross whole.',
    ),
  head: z
    .string()
    .regex(/^(?:[0-9a-f]{40}|[0-9a-f]{64})$/)
    .nullable()
    .describe('The full commit id HEAD named. Null for a repository with no commits yet.'),
  branch: Text(256).nullable().describe('The checked-out branch. Null for a detached HEAD.'),
  at: Timestamp,
  provenance: z.literal('observed'),
});
export type RevisionAnchor = z.infer<typeof RevisionAnchorSchema>;

const Envelope = <F extends string, V extends number>(format: F, version: V) => ({
  format: z.literal(format),
  version: z.literal(version),
  generatedAt: Timestamp,
});

/**
 * `salidium.session-report` version 2: the formalized successor of the browser export.
 *
 * Version 1 is the interface's download button, which embeds the full private projection including
 * prompts, command lines, and output excerpts. It has no schema and is not a consumer contract.
 * Version 2 keeps its envelope and section vocabulary and carries Salidium's findings, not the
 * session's content.
 */
export const SessionReportSchema = z.object({
  ...Envelope('salidium.session-report', 2),
  session: SessionEntrySchema,
  verdict: z.object({
    headline: Text(300),
    tone: z.enum(['pass', 'fail', 'attention', 'working', 'neutral']),
    provenance: ProvenanceSchema,
    because: Text(600).nullable(),
    at: Timestamp.nullable(),
  }),
  latestStatement: StatementSchema.nullable().describe(
    "The agent's latest statement about its work, quoted and attributed.",
  ),
  waiting: z
    .object({
      kind: z.enum(['permission', 'question', 'input']),
      summary: Text(300),
      since: Timestamp,
      provenance: ProvenanceSchema.describe(
        'observed for a permission request, a provider notification, or a question tool call; reported when Salidium read the question in the agent message. The verdict follows it.',
      ),
    })
    .nullable(),
  revision: z
    .object({
      atStart: RevisionAnchorSchema.nullable().describe(
        'When the session started. Kept from the first start Salidium watched. A resume, clear, or compaction does not count as a start, so a session Salidium first watched after it started has none.',
      ),
      atLatestTurnEnd: RevisionAnchorSchema.nullable().describe(
        'When the most recent turn ended. Commits made since then are in changes.commits.',
      ),
    })
    .describe(
      'Which revision the work started from and stands at, each in the repository its root names. Each anchor is null when Salidium did not watch that boundary live: history imports, sessions that began before Salidium was running, or git observation turned off. Added in 1.1.',
    ),
  changes: z.object({
    glance: Text(300),
    files: z.array(ChangedFileSchema).describe('Most recently changed first.'),
    commits: z.array(z.object({ sha: Text(64), at: Timestamp })),
  }),
  verification: z.object({
    glance: Text(300),
    runs: z.array(VerificationRunSchema).describe('Newest first.'),
    latestByMethod: z
      .array(VerificationRunSchema.extend({ laterUnreadable: Count }))
      .describe(
        'The latest run of each method whose outcome could be read, and how many later runs could not.',
      ),
    unverifiedFiles: z.array(Text(4096)),
    statements: z
      .array(StatementSchema)
      .describe('What the agent said about verification. Reported, not observed.'),
  }),
  review: z.object({
    glance: Text(300),
    open: Count,
    resolved: Count,
    groups: z.array(ReviewGroupSchema).describe('Worst severity first, most recent within it.'),
  }),
  remaining: z.object({
    glance: Text(300),
    items: z.array(RemainingItemSchema),
  }),
  explanation: ExplanationSchema,
  usage: z
    .object({
      messages: Count,
      inputTokens: Count,
      outputTokens: Count,
      cacheReadTokens: Count,
      cacheWriteTokens: Count,
    })
    .nullable()
    .describe('Observed tokens only. Null, never zeroes, when none were observed.'),
  ingest: z.object({
    warnings: Count,
    redactions: Count.describe('Credential-shaped spans Salidium removed at ingest.'),
    compactions: Count,
  }),
});
export type SessionReport = z.infer<typeof SessionReportSchema>;

export const SessionListSchema = z.object({
  ...Envelope('salidium.session-list', 1),
  sessions: z.array(SessionEntrySchema).describe('Most recent activity first.'),
  total: Count.describe('Sessions available, before the limit.'),
  truncated: z.boolean(),
});
export type SessionList = z.infer<typeof SessionListSchema>;

export const SessionLookupSchema = z.object({
  ...Envelope('salidium.session-lookup', 1),
  session: SessionEntrySchema,
});
export type SessionLookup = z.infer<typeof SessionLookupSchema>;

/**
 * Written to `$SALIDIUM_HOME/consumer.json` while the daemon runs, and served without a credential
 * at `/consumer/v1/discovery`. It holds no secret.
 */
export const ConsumerContractEntrySchema = z.object({
  // A pattern, not the literal: an entry for a contract added later must not make this document
  // invalid for a consumer that validates the whole array.
  name: z
    .string()
    .regex(/^salidium\.[a-z][a-z0-9-]{0,62}$/)
    .describe(`Use entries named ${CONSUMER_CONTRACT.name}; ignore any other.`),
  major: z.number().int().positive(),
  minor: Count,
  baseUrl: z
    .string()
    .regex(/^http:\/\/127\.0\.0\.1:\d{1,5}\/consumer\/v\d+$/)
    .describe('Loopback only. The endpoints under it are fixed by that major version.'),
});

/**
 * A local contract this daemon serves that is not part of `salidium.consumer` and makes no
 * compatibility promise, such as a version 0 under trial. Added in 1.1.
 */
export const ExperimentalContractEntrySchema = z.object({
  name: z.string().regex(/^salidium\.[a-z][a-z0-9-]{0,40}$/),
  major: z.number().int().nonnegative(),
  minor: z.number().int().nonnegative(),
  baseUrl: z
    .string()
    .regex(/^http:\/\/127\.0\.0\.1:\d{1,5}\/[a-z][a-z0-9-]{0,40}\/v\d+$/)
    .describe('Loopback only.'),
});
export type ExperimentalContractEntry = z.infer<typeof ExperimentalContractEntrySchema>;

export const ConsumerDiscoverySchema = z.object({
  ...Envelope('salidium.consumer-discovery', 1),
  contracts: z
    .array(ConsumerContractEntrySchema)
    .min(1)
    .describe(
      'Every major version this daemon serves. Use the entry whose major you implement and ignore the rest, so a later major never hides this one.',
    ),
  salidium: z.object({ version: Text(64) }),
  providers: z
    .array(z.object({ id: ProviderIdSchema }))
    .max(32)
    .describe(
      "Providers this daemon instance observes, by the id lookup's provider= takes. An id not listed is not observed by this instance until it restarts with a new instanceId. Sorted by id, each once. Added in 1.1: check minor in your contract entry first; a 1.0 daemon does not send it.",
    ),
  experimental: z
    .array(ExperimentalContractEntrySchema)
    .max(8)
    .describe(
      'Experimental local contracts this instance serves. No compatibility promise; consumers must not depend on them without checking. Sorted by name, each once. Added in 1.1.',
    ),
  instanceId: z
    .string()
    .regex(/^[0-9a-f]{32}$/)
    .describe(
      'New on every daemon start. Compare the file with the endpoint before sending a credential to a port.',
    ),
  pid: z.number().int().positive(),
  startedAt: Timestamp,
  authentication: z.object({
    scheme: z.literal('bearer'),
    credential: z.literal('consumer'),
    create: z.literal('salidium consumer create <label>'),
  }),
});
export type ConsumerDiscovery = z.infer<typeof ConsumerDiscoverySchema>;

export const ConsumerErrorCodeSchema = z.enum([
  'host-not-allowed',
  'origin-not-allowed',
  'unauthorized',
  'not-found',
  'session-not-observed',
  'method-not-allowed',
  'bad-request',
  'internal',
]);

export const ConsumerErrorSchema = z.object({
  format: z.literal('salidium.consumer-error'),
  version: z.literal(1),
  error: ConsumerErrorCodeSchema,
  message: Text(300),
});
export type ConsumerError = z.infer<typeof ConsumerErrorSchema>;

/**
 * Change feed messages, one JSON object per server-sent `data:` line.
 *
 * The feed carries notifications, not state: it says a report changed and how to recognize a newer
 * one, and the consumer fetches the report. Every connection starts with `resync`, which means
 * "discard what you think you know and re-read the list". There is no replay, so after any
 * disconnect the consumer reconnects and receives `resync` again. Unknown message types must be
 * ignored.
 */
const FeedBase = <T extends string>(type: T) => ({
  format: z.literal('salidium.session-feed'),
  version: z.literal(1),
  type: z.literal(type),
  at: Timestamp,
});

export const FeedResyncSchema = z.object({
  ...FeedBase('resync'),
  reason: z.literal('connected'),
});

export const FeedSessionChangedSchema = z.object({
  ...FeedBase('session.changed'),
  sessionId: Text(1100),
  native: NativeIdentitySchema,
  evidenceSeq: Count,
  status: SessionStatusSchema,
  explanation: ExplanationStatusSchema,
});

export const FeedSessionRemovedSchema = z.object({
  ...FeedBase('session.removed'),
  sessionId: Text(1100),
  native: NativeIdentitySchema.nullable(),
});

export const FeedHeartbeatSchema = z.object(FeedBase('heartbeat'));

export const FeedClosingSchema = z.object({
  ...FeedBase('closing'),
  reason: z.enum(['credential-revoked', 'shutting-down']),
});

export const FeedMessageSchema = z.discriminatedUnion('type', [
  FeedResyncSchema,
  FeedSessionChangedSchema,
  FeedSessionRemovedSchema,
  FeedHeartbeatSchema,
  FeedClosingSchema,
]);
export type FeedMessage = z.infer<typeof FeedMessageSchema>;
